accounting_web_Bv/urls.py
from django.urls import re_path
from django.views.static import serve
from django.conf import settings


from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounting_web_Bv import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('product/', include('product_app.urls')),
    path('article/', include('article_app.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from home_app import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('contact', views.ContactPeopleView.as_view(), name='contactPeople'),
    path('about-us', views.AboutUsView.as_view(), name='about-us'),
    path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
    path('book', views.AccountingBookView.as_view(), name='book'),
    path('footer', views.FooterPartialView.as_view(), name='footer'),

]

product_app/urls.py
from django.urls import path, re_path

from product_app import views

app_name="product"
urlpatterns = [
    path('list', views.ProductListView.as_view(), name='filelist'),
    re_path('download/(?P<slug>[-\w]+)/', views.ProductDownloadView.as_view(), name='download'),
]

product_app/models.py
from django.db import models
from django.utils.text import slugify


class ExelFiles(models.Model):
    title = models.CharField(max_length=128, verbose_name='عنوان')
    status = models.BooleanField(default=False, verbose_name='وضعیت',
                                 help_text='اگر تیک را بزنید کاربران میتوانند این فایل را مشاهده یا دانلود کنند')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/exel-images', verbose_name='تصویر')
    file = models.FileField(upload_to='exel-files', verbose_name='فایل اکسل')
    slug = models.SlugField(max_length=200, unique=True,editable=True,
                            allow_unicode=True)
    click_count = models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')


    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        super(ExelFiles, self).save()

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'فایل اکسل'
        verbose_name_plural = 'فایل های اکسل'

product_app/views.py
from django.http import FileResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from product_app import models

from django.shortcuts import get_object_or_404, render
from django.utils.encoding import uri_to_iri

class ProductListView(View):
    def get(self, request):
        exel_list = models.ExelFiles.objects.all().order_by('-created').filter(status=True)
        return render(request, 'product_app/product-list.html', {'exel_list':exel_list})


class ProductDownloadView(View):
    def get(self,request, slug):
        exel_files = models.ExelFiles
        exel_file = get_object_or_404(exel_files, slug=uri_to_iri(slug))
        exel_file.click_count += 1
        exel_file.save()
        return FileResponse(exel_file.file, as_attachment=True)

product_app/templates/product_app/product-list.html
{% extends 'Base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}


    <section class="base-container">
        <section class="info-container">

        </section>

        <section class="files-container">
            <section class="title">
                <h1>لیست فایل های کاربردی</h1>
            </section>
            <section class="files-list">
                <ul id="product-image">
                {% if exel_list %}
                    {% for exel in exel_list %}
                        <li>
                        <span>
                            <i class="fa fa-file"></i>
                        <a href="{% url 'product:download' exel.slug %}">
                            {{ exel.title }}
                        </a>
                        </span>
                        <span>
                            <a  href="{% url 'product:download' exel.slug %}">
                                {{ exel.click_count }}<i class="fa fa-download"></i></a>
                            <i id="eye-control" class="fa fa-eye">
                                <img src="{{ exel.image.url }}" alt="{{ exel.title }} تصویر ">
                            </i>
                        </span>
                    </li>
                    {% endfor %}
                {% else %}
                    <section class="no_product">
                        <h2>در حال حاظر هیج فایل قابل دانلود موجود نمی باشد</h2>
                    </section>
                {% endif %}



                </ul>
            </section>

            <section  class="product-image"><img src="" alt=""><i id="product-image-close" class="fa fa-close btn-close white"></i></section>
        </section>
    </section>

{% endblock %}