accounting_web_Bv/urls.py
from django.urls import re_path
from django.views.static import serve
from django.conf import settings


from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounting_web_Bv import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('product/', include('product_app.urls')),
    path('article/', include('article_app.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path
from home_app import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('contact', views.ContactPeopleView.as_view(), name='contactPeople'),
    path('about-us', views.AboutUsView.as_view(), name='about-us'),
    path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
    path('book', views.AccountingBookView.as_view(), name='book'),
    path('footer', views.FooterPartialView.as_view(), name='footer'),

]

home_app/models.py
from django.db import models


# class JobList(models.Model):
#     title = models.CharField(max_length=64, verbose_name='')
#     created = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.title
#
#     class Meta:
#         verbose_name = ''
#         verbose_name_plural = ''
#
#
# class JobListLines(models.Model):
#     job_title = models.ForeignKey(JobList, on_delete=models.CASCADE, related_name='joblist')
#     body = models.TextField(verbose_name='')
#
#     class Meta:
#         verbose_name = ''
#         verbose_name_plural = ''

class AccountingBook(models.Model):
    title = models.CharField(max_length=64, verbose_name="عنوان")
    image = models.ImageField(upload_to='book/main_image', verbose_name='تصویر')
    published = models.BooleanField(default=False, verbose_name="انتشار")
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'کتاب قوانبن'
        verbose_name_plural = 'کتاب'


class AccountingBookLines(models.Model):
    book = models.ForeignKey(AccountingBook, on_delete=models.CASCADE, related_name='lines')
    title = models.CharField(max_length=128, verbose_name='عنوان')
    body = models.TextField(verbose_name='بدنه متن')

    class Meta:
        verbose_name = 'سطر'
        verbose_name_plural = 'سطر ها'


class Customers(models.Model):
    title = models.CharField(max_length=128, verbose_name='نام برند')
    image = models.ImageField(upload_to='customers/images', verbose_name='تصویر برند')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'برند مشتری'
        verbose_name_plural = 'برند مشتریان'


class ContactUsers(models.Model):
    fullname = models.CharField(max_length=256,verbose_name='نام و نام خانوادگی')
    phone = models.PositiveBigIntegerField(verbose_name='شماره موبایل')
    done = models.BooleanField(default=False, verbose_name='در دست انجام')
    note = models.TextField(verbose_name='یادداشت',blank=True,null=True)

    def __str__(self):
        return f'{self.fullname}'

    class Meta:
        verbose_name = 'ارتباط با کاربر'
        verbose_name_plural = 'ارتباط با کاربران'

home_app/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView

from article_app.models import Article
from home_app import models
from home_app.Forms import ContactUsersForm
from home_app.models import ContactUsers


class HomeView(View):
    def get(self, request):
        articles = Article.objects.filter(published=True).order_by('-created')[:6]
        form = ContactUsersForm()
        context = {
            'articles': articles,
            'form': form,
        }
        return render(request, 'home_app/index.html',context)

class ContactPeopleView(View):
    def post(self,request):
        form = ContactUsersForm(data=request.POST)
        query = form.data
        fullname = query.get('fullname')
        phone = int(query.get('phone'))
        if len(str(phone)) == 10:
            ContactUsers.objects.create(fullname=fullname, phone=phone)
        return redirect('home:main')




class AboutUsView(View):
    def get(self, request):
        return render(request, 'home_app/about-us.html',{})


class ContactUsView(View):
    def get(self, request):
        form = ContactUsersForm()
        context = {
            'form': form,
        }
        return render(request, 'home_app/contact-us.html', context)


class AccountingBookView(View):
    def get(self, request):
        book = models.AccountingBook.objects.all().first()
        return render(request, 'home_app/rule-book.html',{'book':book})

class FooterPartialView(TemplateView):
    template_name = 'includes/footer.html'

    def get_context_data(self, **kwargs):
        context = super(FooterPartialView, self).get_context_data()
        context['customers'] = models.Customers.objects.all().order_by('-created')
        return context

home_app/templates/home_app/about-us.html
{% extends 'Base.html' %}
{% load static %}

{% block title %}{% endblock %}


{% block content %}

    <section class="main-content">
        <section class="content-upper">
            <section class="upper-img">
                <img src="{% static 'images/photo_2024-08-16_17-27-00.jpg' %}" alt="main image of iranmehr riaka">
            </section>
            <section class="upper-desc mg-0">
                <section class="address">
                    <p><a title="home page" href="/">صحفه اصلی</a>/<a title="about us page" href="{% url 'home:contact-us' %}">درباره ما</a></p>
                </section>
                <section class="title about-title">
                    <strong>
                        ایرانمهر رایکا
                    </strong>
                    <h1>درباره</h1>
                </section>
                <section class="desc">
                    <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم  و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی قرار گیرد.</p>
                </section>
                <section class="desc">
                    <p>از صنعت چاپ،  را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد،</p>
                </section>
                <section class="desc">
                    <p>.و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز
            </section>
        </section>
    </section>
</section>

<section class="box-container">
    <section class="image"><img title="accounting logo" src="{% static 'images/accounting_.png' %}" alt="accounting logo"></section>
    <section class="list">
        <ul>
            <section class="title">
                <h1>سوالات متداول از ما</h1>
                <i class="fa fa-question-circle-o white"></i>
            </section>
            <li>
                <p>عنوان سوال اینجا قرار میکیرد</p>
                <span class="down block" id="down"></span>
            </li>
            <section class="desc">
                <p>و برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلیتکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژتکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژتکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژتکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژتکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژ تکنولوژی</p>

            </section>
            <li>
                <p> عنوان سوال اینجا قرار میکیرد</p>
                <span class="down block" id="down"></span>
            </li>
            <section class="desc">
                <p>و برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژی</p>

            </section>
            <li>
                <p>عنوان سوال اینجا قرار میکیرد</p>
                <span class="down block" id="down"></span>
            </li>
            <section class="desc">
                <p>و برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژی</p>

            </section>
            <li>
                <p>عنوان سوال اینجا قرار میکیرد</p>
                <span class="down block" id="down"></span>
            </li>
            <section class="desc">
                <p>و برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژی</p>

            </section>
            <li>
                <p> عنوان سوال اینجا قرار میکیرد</p>
                <span class="down block" id="down"></span>
            </li>
            <section class="desc">
                <p>و برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژی</p>

            </section>
            <li>
                <p> عنوان سوال اینجا قرار میکیرد</p>
                <span class="down block" id="down"></span>
            </li>
            <section class="desc">
                <p>و برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژیو برای شرایط فعلی تکنولوژی</p>

            </section>

        </ul>
    </section>
</section>

<section class="joblist-container">
    <section class="joblist-part">
        <section class="title">
            <h6>عنوان لیست کارها</h6>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-1">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z" />
              </svg>
        </section>
        <ul class="desc">
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
        </ul>
    </section>
    <section class="joblist-part">
        <section class="title">
            <h6>عنوان لیست کارها</h6>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-1">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z" />
              </svg>

        </section>
        <ul class="desc">
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
        </ul>
    </section>
</section>
<section class="joblist-container">
    <section class="joblist-part">
        <section class="title">
            <h6>عنوان لیست کارها</h6>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-1">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z" />
              </svg>
        </section>
        <ul class="desc">
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
        </ul>
    </section>
    <section class="joblist-part">
        <section class="title">
            <h6>عنوان لیست کارها</h6>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-1">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 0 0 2.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 0 0-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25ZM6.75 12h.008v.008H6.75V12Zm0 3h.008v.008H6.75V15Zm0 3h.008v.008H6.75V18Z" />
              </svg>

        </section>
        <ul class="desc">
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
            <li>
                <p>نه ای علی الخصوص طراحان خلاقی،  خلاقی، و فرهن  ایجاد کر و فرهن  ایجاد کر فارسی ایجاد کر</p>
            </li>
        </ul>
    </section>
</section>

{% endblock %}

home_app/templates/home_app/contact-us.html
{% extends "Base.html" %}
{% load static %}
{% block title %}{% endblock %}

{% block content %}

    <section class="main-content">
        <section class="content-upper  ">
            <section class="upper-img">
                <iframe title="iranmehrriaka location" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2990.274257380938!2d-70.56068388481569!3d41.45496659976631!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e52963ac45bbcb%3A0xf05e8d125e82af10!2sDos%20Mas!5e0!3m2!1sen!2sus!4v1671220374408!5m2!1sen!2sus" width="600" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </section>
            <section class="upper-desc mg-0">
                <section class="address">
                    <p><a title="home page" href="/">صحفه اصلی</a>/<a title="contact us page" href="{% url 'home:contact-us' %}">تماس با ما</a></p>
                </section>
                <section class="contact-title">
                    <strong> تماس با </strong>
                    <h1>ایرانمهر رایکا </h1>
                </section>
                <section class="contact-desc">
                    <p>راه های ارتباط با ما</p>

                </section>
                <section class="cantact-address">
                    <section class="content right">
                        <ul class="adress-contact">
                            <li>
                                <i class="fa fa-building-o white"></i><span>شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی </span>
                            </li>
                            <li>
                                <i class="fa fa-building-o white"></i><span>شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی </span>
                            </li>
                        </ul>
                    </section>
                </section>
                <section class="content right">
                    <ul class="adress-contact full">
                        <li class="border">
                            <p>عنوان</p>
                            <i class="fa fa-phone white"></i><a title="company phone number" href=""><span>09123456789</span></a>
                        </li>
                        <li class="border">
                            <p>عنوان</p>
                            <i class="fa fa-phone white"></i><a title="company phone number" href=""><span>09123456789</span></a>
                        </li>
                    </ul>
                </section>
        </section>
    </section>
</section>


<section class="contact bg-blue">
    <section class="form-container bg-white">
        <h5>جهت ارتباط سریع تر فرم زیر را پر کنید</h5>
        <p>همکاران ما در اسرع وقت با شما تماس میگیرن</p>
                <form action="{% url 'home:contactPeople' %}" method="post">
                    {% csrf_token %}
                    <div class="both">
                        <label for="name">نام و نام خانوادگی</label>
                        {#                    <input type="text" id="name" name="name" placeholder="نام و نام خانوادگی">#}
                        {{ form.fullname }}
                    </div>
                    <div class="both">
                        <label for="phone">شماره موبایل</label>
                        {#                    <input type="text" id="phone" name="phone" placeholder="شماره موبایل">#}
                        {{ form.phone }}
                    </div>
                    <button type="submit"><span></span>ارسال</button>
                </form>
    </section>
</section>

{% endblock %}

home_app/templates/home_app/rule-book.html
{% extends 'Base.html' %}
{% load static %}

{% block title %}{% endblock %}

{% block content %}

    <section class="article-detail-container">
        <section class="article-info">
            <section class="sticky">
                <section class="book-search-container"  id="searchbar">
                <section class="searchbar">
                    <input type="text" placeholder="عنوان مورد نظر را تایپ کنید">
                    <i class="fa fa-search" id="search-btn"></i>
                </section>
            </section>
            <section class="title">
                <h1>سر فصل های کتاب</h1>
            </section>
            <ul>
                {% if book.lines.all %}
                    {% for line in book.lines.all %}
                        <li onclick="findString('{{ line.title }}')">{{ line.title }}</li>
                    {% endfor %}
                {% endif %}

            </ul>
            </section>
        </section>
        {% if book %}
            <section class="article-main">
                {% if book.title %}
                    <section class="title">
                        <h2 class="book-title">{{ book.title }}</h2>
                    </section>
                {% endif %}
                <section class="detail">
                    {% if book.image.url %}
                        <section class="banner"><img src="{{ book.image.url }}" alt="image of {{ book.title }} book"></section>
                    {% endif %}
                    {% if book.lines.all %}
                        {% for line in book.lines.all %}
                            <section class="title">
                                <h4>{{ line.title }}</h4>
                            </section>
                            <section class="info">
                                <p>{{ line.body }}</p>

                            </section>
                        {% endfor %}
                    {% endif %}
                </section>
            </section>
        {% endif %}
        <section id="scroll-top" class="up-logo">
            <i class="fa fa-arrow-up white"></i>
        </section>
    </section>
    <script src="rule-book.html"></script>
{% endblock %}