accounting_web_Bv/urls.py
from django.urls import re_path
from django.views.static import serve
from django.conf import settings


from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounting_web_Bv import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('product/', include('product_app.urls')),
    path('article/', include('article_app.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_app/urls.py
from django.urls import path, re_path
from article_app import views


app_name="article"
urlpatterns = [
    path('list', views.ArticleListView.as_view(), name='list'),
    path('listq', views.search, name='searchs'),
    path('list/<str:category>', views.CategoryListView.as_view(), name='category-list'),
    path('navbar', views.NavbarPartialView.as_view(), name='navbar'),
    re_path('message/(?P<slug>[-\w]+)/', views.ArticleMessageView.as_view(), name='message'),

    re_path('detail/(?P<slug>[-\w]+)/', views.ArticleDetailView.as_view(), name='detail'),
]

home_app/urls.py
from django.urls import path
from home_app import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('contact', views.ContactPeopleView.as_view(), name='contactPeople'),
    path('about-us', views.AboutUsView.as_view(), name='about-us'),
    path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
    path('book', views.AccountingBookView.as_view(), name='book'),
    path('footer', views.FooterPartialView.as_view(), name='footer'),

]

article_app/models.py
from django.contrib.auth.models import User
from django.db import models




class Category(models.Model):
    title = models.CharField(max_length=128, verbose_name='عنوان')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               blank=True, null=True, verbose_name='نویسنده')
    title = models.CharField(max_length=128, verbose_name='عنوان')
    image = models.ImageField(upload_to='images/article/main',
                              blank=True, null=True, verbose_name='تصویر اصلی')
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 blank=True, null=True, verbose_name='دسته بندی')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False, verbose_name='انتشار')
    slug = models.SlugField(max_length=200, unique=True, editable=True,
                            allow_unicode=True)
    click_count = models.PositiveIntegerField(default=0, verbose_name='بازدید')

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        super(Article, self).save()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


class ArticleInline(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE,
                                related_name='lines', verbose_name='مقاله')
    title = models.CharField(max_length=128, verbose_name='عنوان', blank=True, null=True)
    body = models.TextField(max_length=2048, verbose_name='متن', blank=True, null=True)
    image = models.ImageField(upload_to='images/article/inline', verbose_name='تصویر', blank=True, null=True)

    def __str__(self):
        return f"{self.article} - {self.title}"

    class Meta:
        verbose_name = 'سطر'
        verbose_name_plural= "سطرها"


class ArticleMessage(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='message', verbose_name='مقاله')
    fullname = models.CharField(max_length=128, verbose_name="نام و نام خانوادگی")
    phone = models.PositiveBigIntegerField(verbose_name='شماره موبایل',max_length=11)
    message = models.TextField(verbose_name='پیام',)

    def __str__(self):
        return f'{self.fullname} - {self.message[:50]}...'

    class Meta:
        verbose_name = 'نطر'
        verbose_name_plural = "نظرات"

article_app/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.encoding import uri_to_iri
from django.views import View
from django.views.generic import TemplateView

from article_app import models
from article_app.Forms import ArticleMessageForm


class ArticleListView(View):
    def get(self, request):
        articles = models.Article.objects.all().order_by('-created').filter(published=True)
        page_number = request.GET.get('page')
        paginator = Paginator(articles, 8)
        object_list = paginator.get_page(page_number)
        categories = models.Category.objects.all()
        context = {
            'categories': categories,
            'articles': object_list
        }
        return render(request, 'article_app/article-list.html', context)


class CategoryListView(View):
    def get(self, request, category):
        articles = models.Article.objects.all().order_by('-created').filter(category__title=category,
                                                                                published=True)
        page_number = request.GET.get('page')
        paginator = Paginator(articles, 8)
        object_list = paginator.get_page(page_number)
        categories = models.Category.objects.all()
        context = {
            'categories': categories,
            'articles': object_list
        }
        return render(request, 'article_app/article-list.html', context)

class NavbarPartialView(TemplateView):
    template_name = 'includes/header.html'

    def get_context_data(self, **kwargs):
        context = super(NavbarPartialView, self).get_context_data()
        context['categories'] = models.Category.objects.all()
        return context


class ArticleDetailView(View):

    def get(self, request, slug):
        form = ArticleMessageForm()
        articles = models.Article
        article = get_object_or_404(articles, slug=uri_to_iri(slug))
        article.click_count += 1
        article.save()
        context = {
            'article': article,
            'form': form,
        }
        return render(request, 'article_app/article-detail.html', context)


def search(request):
    q = request.GET.get('q')
    articles = models.Article.objects.filter(title__contains=q, published=True).order_by('-created')
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 8)
    object_list = paginator.get_page(page_number)
    categories = models.Category.objects.all()
    context = {
        'categories': categories,
        'articles': object_list
    }
    return render(request, 'article_app/article-list.html', context)

class ArticleMessageView(View):
    def post(self,request, slug):
        form = ArticleMessageForm(data=request.POST)
        query = form.data
        article = get_object_or_404(models.Article, slug=uri_to_iri(slug))
        fullname = query.get('fullname')
        phone = int(query.get('phone'))
        message = query.get('message')
        if len(str(phone)) == 10:
            models.ArticleMessage.objects.create(fullname=fullname, phone=phone, message=message, article=article)
        form = ArticleMessageForm()
        context = {
            'article': article,
            'form': form,
        }
        return redirect('article:detail',slug=slug)

article_app/templates/article_app/article-detail.html
{% extends 'Base.html' %}
{% load static %}
{% load jalali_tags %}
{% block title %}{% endblock %}

{% block content %}


    <section class="article-detail-container">
        <section class="article-info">
            <section class="address">
                <p><a href="/">صحفه اصلی</a>/<a href="{% url 'article:list' %}">وبلاگ</a>/<a
                        href="{% url 'article:detail' article.slug %}">{{ article.title }}</a></p>
            </section>
            <section class="both">
                <section class="author">
                    <i class="fa fa-user"></i>
                    <strong>:نویسنده </strong>
                    <a rev="made" href="http://instagram.com/_u/{mr.a_xi}"> {{ article.author.first_name }} {{ article.author.last_name }}</a>
                </section>
                <section class="updated_at">
                    <i class="fa fa-calendar"></i>
                    <strong>:تاریخ اپدیت </strong>
                    <p>{{ article.updated|to_jalali:'%y/%m/%d' }}</p>
                </section>
            </section>
        </section>
        <section class="article-main">
            <section class="title">
                <h1>{{ article.title }}</h1>
            </section>
            <section class="detail">
                <section class="banner">
                    <img src="{{ article.image.url }}" alt="{{ article.title }} image">
                </section>
                {% for line in article.lines.all %}
                    {% if line.title %}
                        <section class="title at">
                            <h2>{{ line.title }}</h2>
                        </section>
                    {% endif %}
                    {% if line.body %}
                        <section class="info">
                            <p>{{ line.body }}</p>
                        </section>
                    {% endif %}
                    {% if line.image %}
                        <section class="image">
                            <img src="{{ line.image.url }}" alt="{{ line.title }} image">
                        </section>
                    {% endif %}
                {% endfor %}
            </section>
        </section>
    </section>

    <section class="opinion-form">
        <section class="title">
            <h3>دیدگاهتان را بنویسید</h3>
        </section>
        <form action="{% url 'article:message' article.slug %}" method="post">
            {% csrf_token %}
            <label>نام</label>
            {{ form.fullname }}
            <label>شماره موبایل</label>
            {{form.phone}}
            <label>نظر</label>
            {{form.message}}
            <button>ارسال دیدگاه</button>
        </form>
    </section>


{% endblock %}

article_app/templates/article_app/article-list.html
{% extends "Base.html" %}
{% load static %}
{% load jalali_tags %}

{% block title %}{% endblock %}

{% block content %}
<section class="article-container-list">
    <section class="content-articles">
        <aside>
            <section class="title">
                <h2>دسته بندی مقالات</h2>
            </section>

                <ul class="navbar">
                    {% for category in categories %}
                        <li class="nav-item-articles"><a
                                href="{% url 'article:category-list' category.title %}">{{ category.title }}</a></li>
                    {% endfor %}
                </ul>

        </aside>
        <section class="articles-container">
            <section class="product-container article-container article-page">
                <section class="product-list product-list-page">
                    {% for article in articles %}
                        <section class="single-product single-article">
                             <section class="product-img article-img">
                        {% if article.image %}
                            <a title="image of {{ article.title }} article" title="explore {{article.title }} detail page" href="{% url 'article:detail' article.slug %}">
                        <img src="{{ article.image.url }}" alt="{{ article.title }} image">
                            </a>
                        {% endif %}
                    </section>
                            <section class="article-title">
                                <a href="{% url 'article:detail' article.slug %}">{{ article.title }}</a>
                            </section>
                            <section class="article-down">
                                <p class="date">{{ article.created|to_jalali:'%y/%m/%d' }}</p>
                                <a href="{% url 'article:category-list' article.category.title %}"><p
                                        class="category">{{ article.category.title }}</p></a>

                            </section>
                        </section>

                    {% endfor %}

                </section>
            </section>
        </section>

    </section>
    <!--end on content-->
    <!--pagination-->
    <section class="pagination-container">

        <section class="paginate">
            {% if articles.has_previous %}
            <section class="previous">
                <a href="{% url 'article:list' %}?page={{ articles.previous_page_number }}?q={{ request.GET.q }}" class="fa fa-angle-double-left"></a>
            </section>
            {% endif %}
            <section class="pages">
                {% if articles.has_previous %}
                    <a href="{% url 'article:list' %}?page={{ articles.previous_page_number }}?q={{ request.GET.q }}">{{ articles.previous_page_number }}</a>
                {% endif %}

                <a class="activate">{{ articles.number }}</a>

                {% if articles.has_next %}
                 <a href="{% url 'article:list' %}?page={{ articles.next_page_number }}?q={{ request.GET.q }}">{{ articles.next_page_number }}</a>
                {% endif %}

            </section>
            {% if articles.has_next %}
            <section class="next">
                <a href="{% url 'article:list' %}?page={{ articles.next_page_number }}?q={{ request.GET.q }}" class="fa fa-angle-double-right"></a>
            </section>
            {% endif %}

        </section>
    </section>
</section>
{% endblock %}