accounting_web_Bv/urls.py
from django.urls import re_path
from django.views.static import serve
from django.conf import settings


from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounting_web_Bv import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('product/', include('product_app.urls')),
    path('article/', include('article_app.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_app/urls.py
from django.urls import path, re_path
from article_app import views


app_name="article"
urlpatterns = [
    path('list', views.ArticleListView.as_view(), name='list'),
    path('listq', views.search, name='searchs'),
    path('list/<str:category>', views.CategoryListView.as_view(), name='category-list'),
    path('navbar', views.NavbarPartialView.as_view(), name='navbar'),
    re_path('message/(?P<slug>[-\w]+)/', views.ArticleMessageView.as_view(), name='message'),

    re_path('detail/(?P<slug>[-\w]+)/', views.ArticleDetailView.as_view(), name='detail'),
]

home_app/urls.py
from django.urls import path
from home_app import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('contact', views.ContactPeopleView.as_view(), name='contactPeople'),
    path('about-us', views.AboutUsView.as_view(), name='about-us'),
    path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
    path('book', views.AccountingBookView.as_view(), name='book'),
    path('footer', views.FooterPartialView.as_view(), name='footer'),

]

product_app/urls.py
from django.urls import path, re_path

from product_app import views

app_name="product"
urlpatterns = [
    path('list', views.ProductListView.as_view(), name='filelist'),
    re_path('download/(?P<slug>[-\w]+)/', views.ProductDownloadView.as_view(), name='download'),
]

templates/includes/footer-refrence.html
{% load static %}
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/about.js' %}"></script>
<script src="{% static 'js/product.js' %}"></script>
<script src="{% static 'js/book.js' %}"></script>

templates/includes/footer.html
{% load static %}

<section class="clients-company">
    <section class="title">
        <h5>مشتریان</h5>
    </section>
    <section class="desc">
        <p>شرکت هایی که یه ما اعتماد کرده اند</p>
    </section>
    <section class="clients-list">
        {% for customer in customers %}
            <section class="single-client"><img src="{{ customer.image.url }}" alt="{{ customer.title }} banner">
            </section>

        {% endfor %}

    </section>
</section>
<!-- customers part end -->
<!-- content main part end-->
<footer>
    <section class="down-upper">
        <section class="nav-down">

            <section class="content">
                <section class="title">
                    <h6>صفحات ایرانمهر رایکا</h6>
                </section>
                <ul>
                    <li><a href="{% url 'home:book' %}">کتاب قوانبن</a></li>
                    <li><a href="{% url 'article:list' %}">مقالات </a></li>
                    <li><a href="{% url 'home:about-us' %}">درباره ما</a></li>
                    <li><a href="{% url 'home:contact-us' %}">تماس با ما</a></li>
                    <li><a href="{% url 'product:filelist' %}">فایل های اکسل</a></li>
                </ul>
            </section>
            <section class="social">
                <section class="title">
                    <h6>شبکه های اجتماعی</h6>
                </section>
                <section class="social-list">
                    <a href="https://wa.me/09190323096"><i class="fa fa-whatsapp white"></i></a>
                    <a href="tg://user?id=123456789"><i class="fa fa-telegram white"></i></a>
                    <a href="instagram://user?username={username}"><i class="fa fa-instagram white"></i></a>
                </section>
            </section>
    </section>
    </section>
    <section class="contact-down">
        <section class="title">
            <h6>آدرس ما</h6>
        </section>
        <section class="content">
            <ul class="adress-contact">
                <li>
                    <i class="fa fa-building-o white"></i><span>شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی </span>
                </li>
                <li>
                    <i class="fa fa-phone white"></i><a href="tel:555-666-7777"><span>09123456789</span></a>
                </li>
                <li>
                    <i class="fa fa-phone white"></i><a href="tel:555-666-7777"><span>09123456789</span></a>
                </li>
            </ul>
        </section>
    </section>

    <section class="enamad">
        <a href="#">
            <img src="" alt="enamad logo">
        </a>
        <a class="creator" href="#">
            <strong>: تیم طراحان</strong>
            <p>محمدرضا آقاجانی</p>
        </a>
    </section>
</footer>

templates/includes/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:locale" content="fa_IR" />
    <link rel="stylesheet" href="{% static 'css/css_reset.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/vasir.css' %}">
    <link rel="website icon" type="png" href="{% static 'icons/سایز اصلی.png' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?{% now "U" %}">

templates/includes/header.html
{% load static %}
<header>
    <section class="container">
        <section class="logo">
            <a href="/">
                <img src="{% static 'icons/سایز اصلی.png' %}" alt="logo">
            </a>
        </section>
        <section id="top-bar" class="top-bar">
            <nav>
                <ul class="navbar">
                    <li><a href="{% url 'home:book' %}" id="nav-item-home"
                           class="nav-item{% if request.resolver_match.url_name == 'book' %} active{% endif %}"><i
                            class="fa fa-book"></i>
                        <p>کتاب قوانین</p></a></li>
                    <li><a href="{% url 'article:list' %}"
                           class="nav-item{% if request.resolver_match.url_name == 'list' %} active{% endif %}"
                           id="category"><i
                            class="fa fa-newspaper-o"></i>
                        <p>مقالات</p> <span class="down" id="down"></span></a>

                        <ul class="parent" id="categorylist">
                            {% for category in categories %}
                                <li class="child"><a href="{% url 'article:category-list' category.title %}"
                                                     class="nav-item">{{ category.title }}</a></li>

                            {% endfor %}

                        </ul>

                    </li>
                    <li><a id="nav-item-list"
                           href="{% url 'product:filelist' %}" class="nav-item{% if request.resolver_match.url_name == 'filelist' %} active{% endif %}">
                        <i
                                class="fa fa-file-excel-o"></i>
                        <p>فایل های کاربردی</p></a>
                    </li>
                    <li><a href="{% url 'home:contact-us' %}"
                           class="nav-item{% if request.resolver_match.url_name == 'contact-us' %} active{% endif %} ">
                        <i class="fa fa-address-book"></i>
                        <p>تماس با ما</p></a></li>
                    <li><a href="{% url 'home:about-us' %}"
                           class="nav-item{% if request.resolver_match.url_name == 'about-us' %} active{% endif %} "><i
                            class="fa fa-info-circle"></i>
                        <p>درباره ما </p></a></li>
                </ul>
                <!-- <section class="auth">
                    <section class="part">
                        <i class="fa fa-user"></i>
                        <a href="" class="login">ورود</a>
                    </section>
                    <section class="part">
                        <i class="fa fa-sign-in"></i>
                        <a href="" class="register">ثبت نام</a>
                    </section> -->
                {#                        <section class="auth">#}
                {#                            <section class="part">#}
                {#                                <i class="fa fa-user white"></i>#}
                {#                                <a href="" class="login">پنل کاربر</a>#}
                {#                            </section>#}
                {#                            <section class="part">#}
                {#                                <i class="fa fa-sign-in"></i>#}
                {#                                <a href="" class="register">خروج</a>#}
                {#                            </section>#}
            </nav>
            <div class="exit"><i id="menu_close" class="fa fa-times"></i></div>
        </section>

            <div class="parent">
                <form action="{% url 'article:searchs' %}" method="get">
                <section id="search-bar" class="search-bar">
                    <input type="text" name="q" placeholder="جست و جو در بلاگ..." class="search" id="search">
                    <a id="search-bar-close"><i class="fa fa-times"></i></a>
                </section>
                    </form>
            </div>

        <section class="search-bar-icon">
            <i id="search-bar-open" class="fa fa-search"></i>
        </section>
        <section class="btn-part">
            <a id="menu" class="icon"><i class="fa fa-bars"></i></a>
        </section>

    </section>

</header>